# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perlbal
version:      1.01
version_from: 
installdirs:  vendor
requires:
    BSD::Resource:                 0
    Danga::Socket:                 1.25
    File::Find:                    0
    Linux::AIO:                    1.3
    Net::Netmask:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
