# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perlbal
version:      1.00
version_from: 
installdirs:  site
requires:
    Danga::Socket:                 1.22
    IO::SendFile:                  0.01
    Linux::AIO:                    1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
